#!/usr/bin/env bash
# cross-env — configure builds against a mounted cross-compilation toolchain.
#
# The cpp sandbox image can mount a prebuilt cross toolchain (for example one
# produced by the crosstool-ng image) via `bin/ralph-sandbox --toolchain-dir`.
# This helper inspects that toolchain (pointed to by $CROSS_TOOLCHAIN_DIR) and
# emits ready-to-use build configuration so an agent does not have to hand-roll
# it for every build. It targets GCC-style toolchains (bin/<tuple>-gcc), which is
# what crosstool-ng produces.
set -euo pipefail

die() {
  echo "cross-env: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  cross-env [--dir DIR] <command>

Commands:
  info                   Print the detected toolchain, target tuple and hints (default).
  env                    Print `export` lines (CC/CXX/AR/... + PATH) for `eval`.
  cmake-toolchain [OUT]  Write a CMake toolchain file (OUT path, or - for stdout).
  conan-profile [OUT]    Write a Conan 2 host profile (OUT path, or - for stdout).

DIR defaults to $CROSS_TOOLCHAIN_DIR.
EOF
}

# Globals populated by detect().
TOOLCHAIN_DIR="${CROSS_TOOLCHAIN_DIR:-}"
BIN_DIR=""
TUPLE=""
CC=""
CXX=""
AR=""
RANLIB=""
STRIP=""
LD=""
GCC_MAJOR=""
CMAKE_OS=""
CONAN_OS=""
CMAKE_PROC=""
CONAN_ARCH=""
SYSROOT=""

detect() {
  [[ -n "${TOOLCHAIN_DIR}" ]] || die "no toolchain dir (pass --dir or set CROSS_TOOLCHAIN_DIR)"
  [[ -d "${TOOLCHAIN_DIR}" ]] || die "toolchain dir does not exist: ${TOOLCHAIN_DIR}"

  BIN_DIR="${TOOLCHAIN_DIR}/bin"
  [[ -d "${BIN_DIR}" ]] || die "no bin/ directory under ${TOOLCHAIN_DIR}"

  local gccs=()
  shopt -s nullglob
  gccs=("${BIN_DIR}/"*-gcc)
  shopt -u nullglob
  [[ ${#gccs[@]} -gt 0 ]] || die "no <tuple>-gcc found in ${BIN_DIR}"

  TUPLE="$(basename "${gccs[0]}")"
  TUPLE="${TUPLE%-gcc}"

  CC="${BIN_DIR}/${TUPLE}-gcc"
  CXX="${BIN_DIR}/${TUPLE}-g++"
  AR="${BIN_DIR}/${TUPLE}-ar"
  RANLIB="${BIN_DIR}/${TUPLE}-ranlib"
  STRIP="${BIN_DIR}/${TUPLE}-strip"
  LD="${BIN_DIR}/${TUPLE}-ld"

  GCC_MAJOR="$("${CC}" -dumpversion 2>/dev/null | cut -d. -f1)"
  [[ -n "${GCC_MAJOR}" ]] || GCC_MAJOR="unknown"

  local arch="${TUPLE%%-*}"
  case "${arch}" in
    aarch64 | arm64)
      CMAKE_PROC="aarch64"
      CONAN_ARCH="armv8"
      ;;
    arm*)
      CMAKE_PROC="arm"
      if [[ "${TUPLE}" == *eabihf* ]]; then CONAN_ARCH="armv7hf"; else CONAN_ARCH="armv7"; fi
      ;;
    x86_64)
      CMAKE_PROC="x86_64"
      CONAN_ARCH="x86_64"
      ;;
    i?86)
      CMAKE_PROC="x86"
      CONAN_ARCH="x86"
      ;;
    riscv64)
      CMAKE_PROC="riscv64"
      CONAN_ARCH="riscv64"
      ;;
    powerpc64le | ppc64le)
      CMAKE_PROC="ppc64le"
      CONAN_ARCH="ppc64le"
      ;;
    *)
      CMAKE_PROC="${arch}"
      CONAN_ARCH="${arch}"
      echo "cross-env: warning: unrecognised arch '${arch}'; using it verbatim — override if wrong." >&2
      ;;
  esac

  if [[ "${TUPLE}" == *linux* ]]; then
    CMAKE_OS="Linux"
    CONAN_OS="Linux"
  elif [[ "${TUPLE}" == *-none* || "${TUPLE}" == *-elf* || "${TUPLE}" == *eabi ]]; then
    CMAKE_OS="Generic"
    CONAN_OS="baremetal"
  else
    CMAKE_OS="Linux"
    CONAN_OS="Linux"
    echo "cross-env: warning: could not infer target OS from '${TUPLE}'; defaulting to Linux." >&2
  fi

  SYSROOT=""
  if [[ -d "${TOOLCHAIN_DIR}/${TUPLE}/sysroot" ]]; then
    SYSROOT="${TOOLCHAIN_DIR}/${TUPLE}/sysroot"
  fi
}

emit_or_write() {
  # $1 = destination (- or empty for stdout, otherwise a path). Content on stdin.
  local dest="${1:--}"
  if [[ -z "${dest}" || "${dest}" == "-" ]]; then
    cat
  else
    mkdir -p "$(dirname "${dest}")"
    cat >"${dest}"
    echo "cross-env: wrote ${dest}" >&2
  fi
}

cmd_info() {
  detect
  cat <<EOF
cross-env: detected cross toolchain
  toolchain dir : ${TOOLCHAIN_DIR}
  target tuple  : ${TUPLE}
  gcc version   : ${GCC_MAJOR}
  sysroot       : ${SYSROOT:-<none>}
  CMake system  : ${CMAKE_OS} / ${CMAKE_PROC}
  Conan (os/arch): ${CONAN_OS} / ${CONAN_ARCH}

Next steps:
  eval "\$(cross-env env)"                       # toolchain on PATH + CC/CXX/...
  cross-env cmake-toolchain build/cross.cmake
  cmake -S . -B build --toolchain build/cross.cmake
  cross-env conan-profile build/host.profile
  conan install . -pr:b=default -pr:h=build/host.profile --build=missing
EOF
}

cmd_env() {
  detect
  echo "export PATH=\"${BIN_DIR}:\$PATH\""
  echo "export CC=\"${CC}\""
  echo "export CXX=\"${CXX}\""
  echo "export AR=\"${AR}\""
  echo "export RANLIB=\"${RANLIB}\""
  echo "export STRIP=\"${STRIP}\""
  echo "export LD=\"${LD}\""
  echo "export CROSS_TARGET=\"${TUPLE}\""
}

cmd_cmake_toolchain() {
  detect
  {
    echo "# Generated by cross-env for ${TUPLE}"
    echo "set(CMAKE_SYSTEM_NAME ${CMAKE_OS})"
    echo "set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_PROC})"
    echo "set(CMAKE_C_COMPILER \"${CC}\")"
    echo "set(CMAKE_CXX_COMPILER \"${CXX}\")"
    if [[ -n "${SYSROOT}" ]]; then
      echo "set(CMAKE_SYSROOT \"${SYSROOT}\")"
    fi
    echo "set(CMAKE_FIND_ROOT_PATH \"${TOOLCHAIN_DIR}/${TUPLE}\")"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)"
  } | emit_or_write "${1:--}"
}

cmd_conan_profile() {
  detect
  {
    echo "[settings]"
    echo "os=${CONAN_OS}"
    echo "arch=${CONAN_ARCH}"
    echo "compiler=gcc"
    echo "compiler.version=${GCC_MAJOR}"
    echo "compiler.libcxx=libstdc++11"
    echo "build_type=Release"
    echo ""
    echo "[buildenv]"
    echo "CC=${CC}"
    echo "CXX=${CXX}"
    echo "AR=${AR}"
    echo "RANLIB=${RANLIB}"
    echo "STRIP=${STRIP}"
    echo "LD=${LD}"
  } | emit_or_write "${1:--}"
}

cmd=""
declare -a rest=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir)
      [[ $# -ge 2 ]] || die "--dir requires a value"
      TOOLCHAIN_DIR="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "${cmd}" ]]; then cmd="$1"; else rest+=("$1"); fi
      shift
      ;;
  esac
done

case "${cmd:-info}" in
  info) cmd_info ;;
  env) cmd_env ;;
  cmake-toolchain) cmd_cmake_toolchain "${rest[0]:-}" ;;
  conan-profile) cmd_conan_profile "${rest[0]:-}" ;;
  *) die "unknown command '${cmd}' (try: info, env, cmake-toolchain, conan-profile)" ;;
esac
